### ISSUE TITLE
Integrate with Svelte Vscode plugin

### ISSUE THREAD

**Issue by halfnelson** [halfnelson/svelte-ts#1]
see https://code.visualstudio.com/api/language-extensions/language-server-extension-guide
on first read of the svelte language server, i would probably just need to replace, the 
```js
manager.register(wrapFragmentPlugin(new TypeScriptPlugin(), TypeScriptPlugin.matchFragment));
```
with 
```js
manager.register(new TypescriptPluginThatCanConvertSvelteToTSX())
```

**Comment by simlrh** [comment]
Hey, excellent set of modules, this is exactly what I was looking for / planning to work on myself this weekend! I'm really keen to contribute if possible.

I got your fork of `svelte-language-server` running together with `coc-svelte` inside neovim, and it works great. I also see `svelte-type-checker-vscode` with more recent commits - is this where active development is happening?

I'd really like to use the language server from vim, so I'd be happy to either take over work on `svelte-language-server`, or help to create a separate library that is imported by both `svelte-type-checker-vscode` and `svelte-language-server`.

**Comment by halfnelson** [comment]
`svelte-language-server` is a fork of another project, and the changes I were making seemed to large and unstable for it to be considered something I could PR to upstream. I realized that vs code is happy enough to run multiple language servers and plugins for a particular file type, so started a small from scratch (well, from LSP example) version on the svelte-type-checker-vscode repo. This would allow me a custom release cycle and to work side by side with svelte-language server.

Ideally the common code could be extracted and used by both, since svelte-language-server is really just a combination of other language servers, this would fit in well.

`svelte-type-checker-vscode` has the latest code, it is as far as I have gotten, including hover, and autocomplete

**Comment by simlrh** [comment]
Ah, I missed the vscode branch with newer changes and repeated some of your work!

If you don't mind I'm going to crack on with trying to get your fork into `svelte-language-server` behind an experimental config option - I'm enjoying working on it and learning this stuff.

I *think* https://github.com/simlrh/svelte-language-server/blob/feature/extend-ts-support/src/plugins/ts-svelte/service.ts is a reasonable start for some extractable common code - the language service it returns wraps typescript's language service and handles source code mapping, so it's a drop in replacement for the typescript language service (`TSSveltePlugin` is now just a copy of `TypeScriptPlugin` and I'll remove it later on and make the language service used a config option).

**Comment by halfnelson** [comment]
Thanks for the effort!. This is now a standalone vscode plugin https://github.com/halfnelson/svelte-type-checker-vscode
